spring:
    # [可选]上传文件大小限制
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB
    # REDIS数据库配置
    redis:
        # [可选] 超时时间
        timeout: 10000
        # 以下为单机配置
        # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
        host: 127.0.0.1
        #        # [必须修改] 端口号
        port: 6379
        # [可选] 数据库 DB
        database: 1
        # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
        password: adminadmin123.
        # 以下为集群配置
#        cluster:
#            nodes: 192.168.1.66:9001,192.168.1.66:9002,192.168.1.66:9003,192.168.1.66:9004,192.168.1.66:9005,192.168.1.66:9006
#        password: adminadmin123.
        # [可选] jdbc数据库配置, 项目使用sqlite作为数据库，一般不需要配置
    # mysql数据源
    datasource:
        # kingbase配置
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.kingbase8.Driver
#        url: jdbc:kingbase8://192.168.1.55:54321/wvp?useUnicode=true&characterEncoding=utf8
#        username: system
#        password: system
        # postgresql配置
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: org.postgresql.Driver
#        url: jdbc:postgresql://192.168.1.242:3306/242wvp
#        username: root
#        password: SYceshizu1234
        # mysql配置
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.242:3306/242wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
        username: root
        password: SYceshizu1234


# kingbase 和 postgresql需要开启这个配置
#pagehelper:
#  helper-dialect: postgresql

#[可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
    port: 18080

# 作为28181服务器的配置
sip:
    # [必须修改] 本机的IP
    ip: 192.168.1.3
    # [可选] 28181服务监听的端口
    port: 15060
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    # [可选]
    domain: 3402000001
    # [可选]
    id: 34020000013000000001
    # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
    password: 12345678

#zlm 默认服务器配置
media:
    # [必须修改] zlm服务器唯一id，用于触发hook时区别是哪台服务器,general.mediaServerId
    id: GQ3TF8yT83wh5Wvz
    # [必须修改] zlm服务器的内网IP
    ip: 192.168.1.3
    # [必须修改] zlm服务器的http.port
    http-port: 6080
    # [可选] zlm服务器的hook.admin_params=secret
    secret: 034523TF8yT83wh5Wvz73f7
    # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
    rtp:
        # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
        enable: true
        # [可选] 在此范围内选择端口用于媒体流传输,
        port-range: 30000,30500 # 端口范围
        # [可选] 国标级联在此范围内选择端口发送媒体流，请不要与收流端口范围重合
        send-port-range: 50502,50506 # 端口范围
    # 录像辅助服务， 部署此服务可以实现zlm录像的管理与下载， 0 表示不使用
    record-assist-port: 18089
    # 录像路径
    record-path: ./www/record
    # 录像保存时长
    record-day: 7
# [可选] 日志配置, 一般不需要改
logging:
    config: classpath:logback-spring-local.xml

# [根据业务需求配置]
user-settings:
    server-id: 741266
    auto-apply-play: true
    interface-authentication: true
    interface-authentication-excludes:
        - /api/v1/**
        - /api/media/stream_info_by_app_and_stream
        - /api/v1/control/ptz
        - /api/cloud/record/*/**
    # 推流直播是否录制
    record-push-live: true
    # 国标是否录制
    record-sip: false
    # 使用推流状态作为推流通道状态
    use-pushing-as-status: false
    # 设备上线时是否自动同步通道
    sync-channel-on-device-online: false
     # 消息通道功能-缺少国标ID是否给所有上级发送消息
    send-to-platforms-when-id-lost: false


